os: osx
addons:
  homebrew:
    packages:
    - chromedriver
    
language: python

# command to install dependencies
install:
  - pip install -r req.txt

before_script:
  - ls
  - git config --list
  - git config --global user.email "${github_email}"
  - git config --global user.name "${github_name}"

script:
  - python3 leetcode_generate.py

env:
 global:
   - GH_REPO: github.com/codeyu/leetcode-python.git

after_success:
  - git status
  - git add .
  - git commit -m "update auto by tracis-ci"
  - git push --force "https://${GH_TOKEN}:x-oauth-basic@${GH_REPO}" master:master
