os: osx
osx_image: xcode11.2
addons:
  homebrew:
    casks:
    - chromedriver
    - google-chrome
    
language: shell
cache: pip
python:
  - "3.8"
# command to install dependencies
install:
  - sudo pip3 install -r req.txt

# before_script:
#   - git init
#   - git config --global user.name "codeyu"
#   - git config --global user.email "${github_email}"
#   - git config --list

script:
  - python3 leetcode_generate.py

env:
 global:
   - GH_REPO: github.com/codeyu/leetcode-python.git

# after_success:
#   - git checkout master
#   - git status
#   - git add .
#   - git commit -m "update by Travis CI (JOB $TRAVIS_JOB_NUMBER)"
#   - git remote add origin https://${GH_TOKEN}@${GH_REPO} > /dev/null 2>&1
#   - git push --force --quiet origin master

deploy:
  provider: pages
  target_branch: master
  skip_cleanup: true
  github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
