os: osx
osx_image: xcode11.2
addons:
  homebrew:
    casks:
    - chromedriver
    - google-chrome
    
language: shell
cache: pip
python:
  - "3.8"
# command to install dependencies
install:
  - sudo pip3 install -r req.txt

before_script:
  - git init
  - git config --global user.name "codeyu"
  - git config --global user.email "${github_email}"
  - git config --list

script:
  - python3 leetcode_generate.py

env:
 global:
   - GH_REPO: github.com/codeyu/leetcode-python.git

after_success:
  - git status
  - git add .
  - git commit -m "update auto by tracis-ci"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REPO}" master:master >/dev/null 2>&1
